const _url_host = "https://flutter.eastapple.com";
const url_register = _url_host + "/register";
const url_login = _url_host + "/login";
const url_update_user = _url_host + "/change/user";
const url_post_question = _url_host + "/create/question";
const url_query_question = _url_host + "/query/question";
const url_query_user_header = _url_host + "/query/user";
const url_update_question_relay = _url_host + "/update/relay";
const url_query_question_image = _url_host + "/query/question/image";
